# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
	# check these on https://fabricmc.net/develop
	minecraft_version=1.21.4
	yarn_mappings=1.21.4+build.2
	loader_version=0.16.9

# Mod Properties
	mod_version=2.3.2+1.21.3
	mod_id=quartzelv
	maven_group=atonkish.quartzelv
	archives_base_name=quartz-elevator

# Dependencies
	fabric_version=0.113.0+1.21.4
	mod_menu_version=13.0.0-beta.1
	cloth_config_version=17.0.144

# Distribution platform
	curseforge_id=442509
	modrinth_id=O9C0qdu8
